version: "3.9"
services:
  frontend:
    build: ./services/frontend
    environment:
      - ELIGIBILITY_API_ENDPOINT=http://eligibility-service:9000/predict
    ports:
      - "8000:8000"
    links:
      - eligibility-service
  eligibility-service:
    build: ./services/dummy
    ports:
      - "9000:9000"
  jupyter:
    image: fluescher/jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work:z
    links:
      - mlflow
      - eligibility-service
  mlflow:
    build: ./services/support/mlflow
    ports:
      - "5500:5500"
    volumes:
      - ./artifacts:/tmp/artifacts/
